# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('host_ip', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('cpu_max', models.CharField(max_length=40)),
                ('cpu_used', models.CharField(max_length=40)),
                ('cpu_remain', models.CharField(max_length=40)),
                ('mem_max', models.CharField(max_length=40)),
                ('mem_used', models.CharField(max_length=40)),
                ('mem_remain', models.CharField(max_length=40)),
                ('disk_max', models.CharField(max_length=40)),
                ('disk_used', models.CharField(max_length=40)),
                ('disk_remain', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('int_ip', models.CharField(max_length=40)),
                ('ext_ip', models.CharField(max_length=40)),
                ('vm_id', models.CharField(max_length=40)),
                ('host_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.HostMachine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
