# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtmachine',
            name='vm_status',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
